### 030

In [120]:
import os
import pandas as pd
# meta data 가져오기

wrk_root = "/home/work/hocheol_dir/workspace/datasets/v0.2_data/wrinkle"

label_path = "/home/work/hocheol_dir/workspace/datasets/v0.2_data/wrinkle/NIA_Korean_wholebody_wrinkle_250710.csv"
label_df = pd.read_csv(label_path)
label_df.rename(columns={'periroal': 'perioral'}, inplace=True)
label_df.head()

,filename,성별,나이,forehead,right_eye,left_eye,nasolabial,perioral,right_vol,left_vol
0,0001_face,남자,9,NaN,0,0.0,0,0.0,0.0,0
1,0002_face,남자,9,0.0,0,0.0,0,0.0,0.0,0
2,0003_face,남자,16,NaN,1,0.0,0,0.0,0.0,0
3,0004_face,남자,17,NaN,1,1.0,0,0.0,0.0,0
4,0005_face,남자,17,NaN,0,0.0,0,0.0,0.0,0

In [121]:
os.listdir(os.path.join(wrk_root, '030_data/data'))

['right_eye_0001_face.jpg',
 'left_eye_0001_face.jpg',
 'nasolabial_0001_face.jpg',
 'perioral_0001_face.jpg',
 'right_vol_0001_face.jpg',
 'left_vol_0001_face.jpg',
 'forehead_0002_face.jpg',
 'right_eye_0002_face.jpg',
 'left_eye_0002_face.jpg',
 'nasolabial_0002_face.jpg',
 'perioral_0002_face.jpg',
 'right_vol_0002_face.jpg',
 'left_vol_0002_face.jpg',
 'right_eye_0003_face.jpg',
 'left_eye_0003_face.jpg',
 'nasolabial_0003_face.jpg',
 'perioral_0003_face.jpg',
 'right_vol_0003_face.jpg',
 'left_vol_0003_face.jpg',
 'right_eye_0004_face.jpg',
 'left_eye_0004_face.jpg',
 'nasolabial_0004_face.jpg',
 'perioral_0004_face.jpg',
 'right_vol_0004_face.jpg',
 'left_vol_0004_face.jpg',
 'right_eye_0005_face.jpg',
 'left_eye_0005_face.jpg',
 'nasolabial_0005_face.jpg',
 'perioral_0005_face.jpg',
 'right_vol_0005_face.jpg',
 'left_vol_0005_face.jpg',
 'right_eye_0006_face.jpg',
 'left_eye_0006_face.jpg',
 'nasolabial_0006_face.jpg',
 'perioral_0006_face.jpg',
 'right_vol_0006_face.jpg',
 'left_vol_0006_face.jpg',
 'right_eye_0008_face.jpg',
 'left_eye_0008_face.jpg',
 'nasolabial_0008_face.jpg',
 'perioral_0008_face.jpg',
 'right_vol_0008_face.jpg',
 'left_vol_0008_face.jpg',
 'right_eye_0013_face.jpg',
 'left_eye_0013_face.jpg',
 'nasolabial_0013_face.jpg',
 'perioral_0013_face.jpg',
 'right_vol_0013_face.jpg',
 'left_vol_0013_face.jpg',
 'forehead_0014_face.jpg',
 'right_eye_0014_face.jpg',
 'left_eye_0014_face.jpg',
 'nasolabial_0014_face.jpg',
 'perioral_0014_face.jpg',
 'right_vol_0014_face.jpg',
 'left_vol_0014_face.jpg',
 'forehead_0016_face.jpg',
 'right_eye_0016_face.jpg',
 'left_eye_0016_face.jpg',
 'nasolabial_0016_face.jpg',
 'perioral_0016_face.jpg',
 'right_vol_0016_face.jpg',
 'left_vol_0016_face.jpg',
 'right_eye_0017_face.jpg',
 'left_eye_0017_face.jpg',
 'nasolabial_0017_face.jpg',
 'perioral_0017_face.jpg',
 'right_vol_0017_face.jpg',
 'left_vol_0017_face.jpg',
 'forehead_0018_face.jpg',
 'right_eye_0018_face.jpg',
 'left_eye_0018_face.jpg',
 'nasolabial_0018_face.jpg',
 'perioral_0018_face.jpg',
 'right_vol_0018_face.jpg',
 'left_vol_0018_face.jpg',
 'right_eye_0019_face.jpg',
 'left_eye_0019_face.jpg',
 'nasolabial_0019_face.jpg',
 'perioral_0019_face.jpg',
 'right_vol_0019_face.jpg',
 'left_vol_0019_face.jpg',
 'right_eye_0020_face.jpg',
 'left_eye_0020_face.jpg',
 'nasolabial_0020_face.jpg',
 'perioral_0020_face.jpg',
 'right_vol_0020_face.jpg',
 'left_vol_0020_face.jpg',
 'right_eye_0021_face.jpg',
 'left_eye_0021_face.jpg',
 'nasolabial_0021_face.jpg',
 'perioral_0021_face.jpg',
 'right_vol_0021_face.jpg',
 'left_vol_0021_face.jpg',
 'right_eye_0022_face.jpg',
 'left_eye_0022_face.jpg',
 'nasolabial_0022_face.jpg',
 'perioral_0022_face.jpg',
 'right_vol_0022_face.jpg',
 'left_vol_0022_face.jpg',
 'forehead_0023_face.jpg',
 'right_eye_0023_face.jpg',
 'left_eye_0023_face.jpg',
 'nasolabial_0023_face.jpg',
 'perioral_0023_face.jpg',
 'right_vol_0023_face.jpg',
 'left_vol_0023_face.jpg',
 'forehead_0024_face.jpg',
 'right_eye_0024_face.jpg',
 'left_eye_0024_face.jpg',
 'nasolabial_0024_face.jpg',
 'perioral_0024_face.jpg',
 'right_vol_0024_face.jpg',
 'left_vol_0024_face.jpg',
 'forehead_0026_face.jpg',
 'right_eye_0026_face.jpg',
 'left_eye_0026_face.jpg',
 'nasolabial_0026_face.jpg',
 'perioral_0026_face.jpg',
 'right_vol_0026_face.jpg',
 'left_vol_0026_face.jpg',
 'right_eye_0027_face.jpg',
 'left_eye_0027_face.jpg',
 'nasolabial_0027_face.jpg',
 'perioral_0027_face.jpg',
 'right_vol_0027_face.jpg',
 'left_vol_0027_face.jpg',
 'right_eye_0028_face.jpg',
 'left_eye_0028_face.jpg',
 'nasolabial_0028_face.jpg',
 'perioral_0028_face.jpg',
 'right_vol_0028_face.jpg',
 'left_vol_0028_face.jpg',
 'right_eye_0029_face.jpg',
 'left_eye_0029_face.jpg',
 'nasolabial_0029_face.jpg',
 'perioral_0029_face.jpg',
 'right_vol_0029_face.jpg',
 'left_vol_0029_face.jpg',
 'right_eye_0031_face.jpg',
 'left_eye_0031_face.jpg',
 'nasolabial_0031_face.jpg',
 'perioral_0031_face.jpg',
 'right_vol_0031_face.jpg',
 'left_vol_0031_face.jpg',
 'forehead_0034_face.jpg',
 'right_eye_0034_face.jpg',
 'left_eye_0034_face.jpg',
 'nasolabial_0034_face.jpg',
 'perioral_0034_face.jpg',
 'right_vol_0034_face.jpg',
 'left_vol_0034_face.jpg',
 'right_eye_0035_face.jpg',
 'left_eye_0035_face.jpg',
 'nasolabial_0035_face.jpg',
 'perioral_0035_face.jpg',
 'right_vol_0035_face.jpg',
 'left_vol_0035_face.jpg',
 'right_eye_0036_face.jpg',
 'left_eye_0036_face.jpg',
 'nasolabial_0036_face.jpg',
 'perioral_0036_face.jpg',
 'right_vol_0036_face.jpg',
 'left_vol_0036_face.jpg',
 'right_eye_0037_face.jpg',
 'left_eye_0037_face.jpg',
 'nasolabial_0037_face.jpg',
 'perioral_0037_face.jpg',
 'right_vol_0037_face.jpg',
 'left_vol_0037_face.jpg',
 'right_eye_0039_face.jpg',
 'left_eye_0039_face.jpg',
 'nasolabial_0039_face.jpg',
 'perioral_0039_face.jpg',
 'right_vol_0039_face.jpg',
 'left_vol_0039_face.jpg',
 'right_eye_0044_face.jpg',
 'left_eye_0044_face.jpg',
 'nasolabial_0044_face.jpg',
 'perioral_0044_face.jpg',
 'right_vol_0044_face.jpg',
 'left_vol_0044_face.jpg',
 'right_eye_0045_face.jpg',
 'left_eye_0045_face.jpg',
 'nasolabial_0045_face.jpg',
 'perioral_0045_face.jpg',
 'right_vol_0045_face.jpg',
 'left_vol_0045_face.jpg',
 'forehead_0046_face.jpg',
 'right_eye_0046_face.jpg',
 'left_eye_0046_face.jpg',
 'nasolabial_0046_face.jpg',
 'perioral_0046_face.jpg',
 'right_vol_0046_face.jpg',
 'left_vol_0046_face.jpg',
 'right_eye_0047_face.jpg',
 'left_eye_0047_face.jpg',
 'nasolabial_0047_face.jpg',
 'perioral_0047_face.jpg',
 'right_vol_0047_face.jpg',
 'left_vol_0047_face.jpg',
 'right_eye_0048_face.jpg',
 'left_eye_0048_face.jpg',
 'nasolabial_0048_face.jpg',
 'perioral_0048_face.jpg',
 'right_vol_0048_face.jpg',
 'left_vol_0048_face.jpg',
 'right_eye_0049_face.jpg',
 'left_eye_0049_face.jpg',
 'nasolabial_0049_face.jpg',
 'perioral_0049_face.jpg',
 'right_vol_0049_face.jpg',
 'left_vol_0049_face.jpg',
 'right_eye_0050_face.jpg',
 'left_eye_0050_face.jpg',
 'nasolabial_0050_face.jpg',
 'perioral_0050_face.jpg',
 'right_vol_0050_face.jpg',
 'left_vol_0050_face.jpg',
 'right_eye_0051_face.jpg',
 'left_eye_0051_face.jpg',
 'nasolabial_0051_face.jpg',
 'perioral_0051_face.jpg',
 'right_vol_0051_face.jpg',
 'left_vol_0051_face.jpg',
 'right_eye_0052_face.jpg',
 'left_eye_0052_face.jpg',
 'nasolabial_0052_face.jpg',
 'perioral_0052_face.jpg',
 'right_vol_0052_face.jpg',
 'left_vol_0052_face.jpg',
 'right_eye_0053_face.jpg',
 'left_eye_0053_face.jpg',
 'nasolabial_0053_face.jpg',
 'perioral_0053_face.jpg',
 'right_vol_0053_face.jpg',
 'left_vol_0053_face.jpg',
 'right_eye_0054_face.jpg',
 'left_eye_0054_face.jpg',
 'nasolabial_0054_face.jpg',
 'perioral_0054_face.jpg',
 'right_vol_0054_face.jpg',
 'left_vol_0054_face.jpg',
 'right_eye_0055_face.jpg',
 'left_eye_0055_face.jpg',
 'nasolabial_0055_face.jpg',
 'perioral_0055_face.jpg',
 'right_vol_0055_face.jpg',
 'left_vol_0055_face.jpg',
 'right_eye_0056_face.jpg',
 'left_eye_0056_face.jpg',
 'nasolabial_0056_face.jpg',
 'perioral_0056_face.jpg',
 'right_vol_0056_face.jpg',
 'left_vol_0056_face.jpg',
 'right_eye_0057_face.jpg',
 'left_eye_0057_face.jpg',
 'nasolabial_0057_face.jpg',
 'perioral_0057_face.jpg',
 'right_vol_0057_face.jpg',
 'left_vol_0057_face.jpg',
 'right_eye_0058_face.jpg',
 'left_eye_0058_face.jpg',
 'nasolabial_0058_face.jpg',
 'perioral_0058_face.jpg',
 'right_vol_0058_face.jpg',
 'left_vol_0058_face.jpg',
 'right_eye_0063_face.jpg',
 'left_eye_0063_face.jpg',
 'nasolabial_0063_face.jpg',
 'perioral_0063_face.jpg',
 'right_vol_0063_face.jpg',
 'left_vol_0063_face.jpg',
 'right_eye_0064_face.jpg',
 'left_eye_0064_face.jpg',
 'nasolabial_0064_face.jpg',
 'perioral_0064_face.jpg',
 'right_vol_0064_face.jpg',
 'left_vol_0064_face.jpg',
 'right_eye_0065_face.jpg',
 'left_eye_0065_face.jpg',
 'nasolabial_0065_face.jpg',
 'perioral_0065_face.jpg',
 'right_vol_0065_face.jpg',
 'left_vol_0065_face.jpg',
 'right_eye_0066_face.jpg',
 'left_eye_0066_face.jpg',
 'nasolabial_0066_face.jpg',
 'perioral_0066_face.jpg',
 'right_vol_0066_face.jpg',
 'left_vol_0066_face.jpg',
 'right_eye_0067_face.jpg',
 'left_eye_0067_face.jpg',
 'nasolabial_0067_face.jpg',
 'perioral_0067_face.jpg',
 'right_vol_0067_face.jpg',
 'left_vol_0067_face.jpg',
 'forehead_0068_face.jpg',
 'right_eye_0068_face.jpg',
 'left_eye_0068_face.jpg',
 'nasolabial_0068_face.jpg',
 'perioral_0068_face.jpg',
 'right_vol_0068_face.jpg',
 'left_vol_0068_face.jpg',
 'forehead_0069_face.jpg',
 'right_eye_0069_face.jpg',
 'left_eye_0069_face.jpg',
 'nasolabial_0069_face.jpg',
 'perioral_0069_face.jpg',
 'right_vol_0069_face.jpg',
 'left_vol_0069_face.jpg',
 'right_eye_0070_face.jpg',
 'left_eye_0070_face.jpg',
 'nasolabial_0070_face.jpg',
 'perioral_0070_face.jpg',
 'right_vol_0070_face.jpg',
 'left_vol_0070_face.jpg',
 'right_eye_0071_face.jpg',
 'left_eye_0071_face.jpg',
 'nasolabial_0071_face.jpg',
 'perioral_0071_face.jpg',
 'right_vol_0071_face.jpg',
 'left_vol_0071_face.jpg',
 'right_eye_0073_face.jpg',
 'left_eye_0073_face.jpg',
 'nasolabial_0073_face.jpg',
 'perioral_0073_face.jpg',
 'right_vol_0073_face.jpg',
 'left_vol_0073_face.jpg',
 'right_eye_0075_face.jpg',
 'left_eye_0075_face.jpg',
 'nasolabial_0075_face.jpg',
 'perioral_0075_face.jpg',
 'right_vol_0075_face.jpg',
 'left_vol_0075_face.jpg',
 'right_eye_0077_face.jpg',
 'left_eye_0077_face.jpg',
 'nasolabial_0077_face.jpg',
 'perioral_0077_face.jpg',
 'right_vol_0077_face.jpg',
 'left_vol_0077_face.jpg',
 'forehead_0078_face.jpg',
 'right_eye_0078_face.jpg',
 'left_eye_0078_face.jpg',
 'nasolabial_0078_face.jpg',
 'perioral_0078_face.jpg',
 'right_vol_0078_face.jpg',
 'left_vol_0078_face.jpg',
 'right_eye_0079_face.jpg',
 'left_eye_0079_face.jpg',
 'nasolabial_0079_face.jpg',
 'perioral_0079_face.jpg',
 'right_vol_0079_face.jpg',
 'left_vol_0079_face.jpg',
 'right_eye_0080_face.jpg',
 'left_eye_0080_face.jpg',
 'nasolabial_0080_face.jpg',
 'perioral_0080_face.jpg',
 'right_vol_0080_face.jpg',
 'left_vol_0080_face.jpg',
 'right_eye_0081_face.jpg',
 'left_eye_0081_face.jpg',
 'nasolabial_0081_face.jpg',
 'perioral_0081_face.jpg',
 'right_vol_0081_face.jpg',
 'left_vol_0081_face.jpg',
 'forehead_0082_face.jpg',
 'right_eye_0082_face.jpg',
 'left_eye_0082_face.jpg',
 'nasolabial_0082_face.jpg',
 'perioral_0082_face.jpg',
 'right_vol_0082_face.jpg',
 'left_vol_0082_face.jpg',
 'right_eye_0083_face.jpg',
 'left_eye_0083_face.jpg',
 'nasolabial_0083_face.jpg',
 'perioral_0083_face.jpg',
 'right_vol_0083_face.jpg',
 'left_vol_0083_face.jpg',
 'right_eye_0084_face.jpg',
 'left_eye_0084_face.jpg',
 'nasolabial_0084_face.jpg',
 'perioral_0084_face.jpg',
 'right_vol_0084_face.jpg',
 'left_vol_0084_face.jpg',
 'right_eye_0085_face.jpg',
 'left_eye_0085_face.jpg',
 'nasolabial_0085_face.jpg',
 'perioral_0085_face.jpg',
 'right_vol_0085_face.jpg',
 'left_vol_0085_face.jpg',
 'right_eye_0086_face.jpg',
 'left_eye_0086_face.jpg',
 'nasolabial_0086_face.jpg',
 'perioral_0086_face.jpg',
 'right_vol_0086_face.jpg',
 'left_vol_0086_face.jpg',
 'right_eye_0088_face.jpg',
 'left_eye_0088_face.jpg',
 'nasolabial_0088_face.jpg',
 'perioral_0088_face.jpg',
 'right_vol_0088_face.jpg',
 'left_vol_0088_face.jpg',
 'right_eye_0089_face.jpg',
 'left_eye_0089_face.jpg',
 'nasolabial_0089_face.jpg',
 'perioral_0089_face.jpg',
 'right_vol_0089_face.jpg',
 'left_vol_0089_face.jpg',
 'right_eye_0090_face.jpg',
 'left_eye_0090_face.jpg',
 'nasolabial_0090_face.jpg',
 'perioral_0090_face.jpg',
 'right_vol_0090_face.jpg',
 'left_vol_0090_face.jpg',
 'right_eye_0091_face.jpg',
 'left_eye_0091_face.jpg',
 'nasolabial_0091_face.jpg',
 'perioral_0091_face.jpg',
 'right_vol_0091_face.jpg',
 'left_vol_0091_face.jpg',
 'right_eye_0092_face.jpg',
 'left_eye_0092_face.jpg',
 'nasolabial_0092_face.jpg',
 'perioral_0092_face.jpg',
 'right_vol_0092_face.jpg',
 'left_vol_0092_face.jpg',
 'right_eye_0093_face.jpg',
 'left_eye_0093_face.jpg',
 'nasolabial_0093_face.jpg',
 'perioral_0093_face.jpg',
 'right_vol_0093_face.jpg',
 'left_vol_0093_face.jpg',
 'right_eye_0094_face.jpg',
 'left_eye_0094_face.jpg',
 'nasolabial_0094_face.jpg',
 'perioral_0094_face.jpg',
 'right_vol_0094_face.jpg',
 'left_vol_0094_face.jpg',
 'forehead_0095_face.jpg',
 'right_eye_0095_face.jpg',
 'left_eye_0095_face.jpg',
 'nasolabial_0095_face.jpg',
 'perioral_0095_face.jpg',
 'right_vol_0095_face.jpg',
 'left_vol_0095_face.jpg',
 'forehead_0096_face.jpg',
 'right_eye_0096_face.jpg',
 'left_eye_0096_face.jpg',
 'nasolabial_0096_face.jpg',
 'perioral_0096_face.jpg',
 'right_vol_0096_face.jpg',
 'left_vol_0096_face.jpg',
 'forehead_0097_face.jpg',
 'right_eye_0097_face.jpg',
 'left_eye_0097_face.jpg',
 'nasolabial_0097_face.jpg',
 'perioral_0097_face.jpg',
 'right_vol_0097_face.jpg',
 'left_vol_0097_face.jpg',
 'right_eye_0098_face.jpg',
 'left_eye_0098_face.jpg',
 'nasolabial_0098_face.jpg',
 'perioral_0098_face.jpg',
 'right_vol_0098_face.jpg',
 'left_vol_0098_face.jpg',
 'right_eye_0099_face.jpg',
 'left_eye_0099_face.jpg',
 'nasolabial_0099_face.jpg',
 'perioral_0099_face.jpg',
 'right_vol_0099_face.jpg',
 'left_vol_0099_face.jpg',
 'right_eye_0101_face.jpg',
 'left_eye_0101_face.jpg',
 'nasolabial_0101_face.jpg',
 'perioral_0101_face.jpg',
 'right_vol_0101_face.jpg',
 'left_vol_0101_face.jpg',
 'right_eye_0102_face.jpg',
 'left_eye_0102_face.jpg',
 'nasolabial_0102_face.jpg',
 'perioral_0102_face.jpg',
 'right_vol_0102_face.jpg',
 'left_vol_0102_face.jpg',
 'right_eye_0103_face.jpg',
 'left_eye_0103_face.jpg',
 'nasolabial_0103_face.jpg',
 'perioral_0103_face.jpg',
 'right_vol_0103_face.jpg',
 'left_vol_0103_face.jpg',
 'right_eye_0104_face.jpg',
 'left_eye_0104_face.jpg',
 'nasolabial_0104_face.jpg',
 'perioral_0104_face.jpg',
 'right_vol_0104_face.jpg',
 'left_vol_0104_face.jpg',
 'right_eye_0105_face.jpg',
 'left_eye_0105_face.jpg',
 'nasolabial_0105_face.jpg',
 'perioral_0105_face.jpg',
 'right_vol_0105_face.jpg',
 'left_vol_0105_face.jpg',
 'forehead_0106_face.jpg',
 'right_eye_0106_face.jpg',
 'left_eye_0106_face.jpg',
 'nasolabial_0106_face.jpg',
 'perioral_0106_face.jpg',
 'right_vol_0106_face.jpg',
 'left_vol_0106_face.jpg',
 'right_eye_0107_face.jpg',
 'left_eye_0107_face.jpg',
 'nasolabial_0107_face.jpg',
 'perioral_0107_face.jpg',
 'right_vol_0107_face.jpg',
 'left_vol_0107_face.jpg',
 'right_eye_0108_face.jpg',
 'left_eye_0108_face.jpg',
 'nasolabial_0108_face.jpg',
 'perioral_0108_face.jpg',
 'right_vol_0108_face.jpg',
 'left_vol_0108_face.jpg',
 'right_eye_0109_face.jpg',
 'left_eye_0109_face.jpg',
 'nasolabial_0109_face.jpg',
 'perioral_0109_face.jpg',
 'right_vol_0109_face.jpg',
 'left_vol_0109_face.jpg',
 'forehead_0110_face.jpg',
 'right_eye_0110_face.jpg',
 'left_eye_0110_face.jpg',
 'nasolabial_0110_face.jpg',
 'perioral_0110_face.jpg',
 'right_vol_0110_face.jpg',
 'left_vol_0110_face.jpg',
 'right_eye_0111_face.jpg',
 'left_eye_0111_face.jpg',
 'nasolabial_0111_face.jpg',
 'perioral_0111_face.jpg',
 'right_vol_0111_face.jpg',
 'left_vol_0111_face.jpg',
 'right_eye_0112_face.jpg',
 'left_eye_0112_face.jpg',
 'nasolabial_0112_face.jpg',
 'perioral_0112_face.jpg',
 'right_vol_0112_face.jpg',
 'left_vol_0112_face.jpg',
 'right_eye_0113_face.jpg',
 'left_eye_0113_face.jpg',
 'nasolabial_0113_face.jpg',
 'perioral_0113_face.jpg',
 'right_vol_0113_face.jpg',
 'left_vol_0113_face.jpg',
 'right_eye_0114_face.jpg',
 'left_eye_0114_face.jpg',
 'nasolabial_0114_face.jpg',
 'perioral_0114_face.jpg',
 'right_vol_0114_face.jpg',
 'left_vol_0114_face.jpg',
 'right_eye_0116_face.jpg',
 'left_eye_0116_face.jpg',
 'nasolabial_0116_face.jpg',
 'perioral_0116_face.jpg',
 'right_vol_0116_face.jpg',
 'left_vol_0116_face.jpg',
 'forehead_0117_face.jpg',
 'right_eye_0117_face.jpg',
 'left_eye_0117_face.jpg',
 'nasolabial_0117_face.jpg',
 'perioral_0117_face.jpg',
 'right_vol_0117_face.jpg',
 'left_vol_0117_face.jpg',
 'forehead_0118_face.jpg',
 'right_eye_0118_face.jpg',
 'left_eye_0118_face.jpg',
 'nasolabial_0118_face.jpg',
 'perioral_0118_face.jpg',
 'right_vol_0118_face.jpg',
 'left_vol_0118_face.jpg',
 'forehead_0120_face.jpg',
 'right_eye_0120_face.jpg',
 'left_eye_0120_face.jpg',
 'nasolabial_0120_face.jpg',
 'perioral_0120_face.jpg',
 'right_vol_0120_face.jpg',
 'left_vol_0120_face.jpg',
 'right_eye_0121_face.jpg',
 'left_eye_0121_face.jpg',
 'nasolabial_0121_face.jpg',
 'perioral_0121_face.jpg',
 'right_vol_0121_face.jpg',
 'left_vol_0121_face.jpg',
 'right_eye_0122_face.jpg',
 'left_eye_0122_face.jpg',
 'nasolabial_0122_face.jpg',
 'perioral_0122_face.jpg',
 'right_vol_0122_face.jpg',
 'left_vol_0122_face.jpg',
 'right_eye_0123_face.jpg',
 'left_eye_0123_face.jpg',
 'nasolabial_0123_face.jpg',
 'perioral_0123_face.jpg',
 'right_vol_0123_face.jpg',
 'left_vol_0123_face.jpg',
 'forehead_0124_face.jpg',
 'right_eye_0124_face.jpg',
 'left_eye_0124_face.jpg',
 'nasolabial_0124_face.jpg',
 'perioral_0124_face.jpg',
 'right_vol_0124_face.jpg',
 'left_vol_0124_face.jpg',
 'right_eye_0126_face.jpg',
 'left_eye_0126_face.jpg',
 'nasolabial_0126_face.jpg',
 'perioral_0126_face.jpg',
 'right_vol_0126_face.jpg',
 'left_vol_0126_face.jpg',
 'right_eye_0128_face.jpg',
 'left_eye_0128_face.jpg',
 'nasolabial_0128_face.jpg',
 'perioral_0128_face.jpg',
 'right_vol_0128_face.jpg',
 'left_vol_0128_face.jpg',
 'forehead_0129_face.jpg',
 'right_eye_0129_face.jpg',
 'left_eye_0129_face.jpg',
 'nasolabial_0129_face.jpg',
 'perioral_0129_face.jpg',
 'right_vol_0129_face.jpg',
 'left_vol_0129_face.jpg',
 'right_eye_0130_face.jpg',
 'left_eye_0130_face.jpg',
 'nasolabial_0130_face.jpg',
 'perioral_0130_face.jpg',
 'right_vol_0130_face.jpg',
 'left_vol_0130_face.jpg',
 'right_eye_0131_face.jpg',
 'left_eye_0131_face.jpg',
 'nasolabial_0131_face.jpg',
 'perioral_0131_face.jpg',
 'right_vol_0131_face.jpg',
 'left_vol_0131_face.jpg',
 'forehead_0132_face.jpg',
 'right_eye_0132_face.jpg',
 'left_eye_0132_face.jpg',
 'nasolabial_0132_face.jpg',
 'perioral_0132_face.jpg',
 'right_vol_0132_face.jpg',
 'left_vol_0132_face.jpg',
 'right_eye_0133_face.jpg',
 'left_eye_0133_face.jpg',
 'nasolabial_0133_face.jpg',
 'perioral_0133_face.jpg',
 'right_vol_0133_face.jpg',
 'left_vol_0133_face.jpg',
 'right_eye_0134_face.jpg',
 'left_eye_0134_face.jpg',
 'nasolabial_0134_face.jpg',
 'perioral_0134_face.jpg',
 'right_vol_0134_face.jpg',
 'left_vol_0134_face.jpg',
 'right_eye_0135_face.jpg',
 'left_eye_0135_face.jpg',
 'nasolabial_0135_face.jpg',
 'perioral_0135_face.jpg',
 'right_vol_0135_face.jpg',
 'left_vol_0135_face.jpg',
 'forehead_0136_face.jpg',
 'right_eye_0136_face.jpg',
 'left_eye_0136_face.jpg',
 'nasolabial_0136_face.jpg',
 'perioral_0136_face.jpg',
 'right_vol_0136_face.jpg',
 'left_vol_0136_face.jpg',
 'right_eye_0137_face.jpg',
 'left_eye_0137_face.jpg',
 'nasolabial_0137_face.jpg',
 'perioral_0137_face.jpg',
 'right_vol_0137_face.jpg',
 'left_vol_0137_face.jpg',
 'right_eye_0139_face.jpg',
 'left_eye_0139_face.jpg',
 'nasolabial_0139_face.jpg',
 'perioral_0139_face.jpg',
 'right_vol_0139_face.jpg',
 'left_vol_0139_face.jpg',
 'right_eye_0140_face.jpg',
 'left_eye_0140_face.jpg',
 'nasolabial_0140_face.jpg',
 'perioral_0140_face.jpg',
 'right_vol_0140_face.jpg',
 'left_vol_0140_face.jpg',
 'right_eye_0142_face.jpg',
 'left_eye_0142_face.jpg',
 'nasolabial_0142_face.jpg',
 'perioral_0142_face.jpg',
 'right_vol_0142_face.jpg',
 'left_vol_0142_face.jpg',
 'right_eye_0143_face.jpg',
 'left_eye_0143_face.jpg',
 'nasolabial_0143_face.jpg',
 'perioral_0143_face.jpg',
 'right_vol_0143_face.jpg',
 'left_vol_0143_face.jpg',
 'right_eye_0144_face.jpg',
 'left_eye_0144_face.jpg',
 'nasolabial_0144_face.jpg',
 'perioral_0144_face.jpg',
 'right_vol_0144_face.jpg',
 'left_vol_0144_face.jpg',
 'right_eye_0145_face.jpg',
 'left_eye_0145_face.jpg',
 'nasolabial_0145_face.jpg',
 'perioral_0145_face.jpg',
 'right_vol_0145_face.jpg',
 'left_vol_0145_face.jpg',
 'right_eye_0146_face.jpg',
 'left_eye_0146_face.jpg',
 'nasolabial_0146_face.jpg',
 'perioral_0146_face.jpg',
 'right_vol_0146_face.jpg',
 'left_vol_0146_face.jpg',
 'right_eye_0147_face.jpg',
 'left_eye_0147_face.jpg',

In [122]:
len(os.listdir(os.path.join(wrk_root, '030_data/data')))

10932

In [123]:
# image path 가져오기
import os
import re

exts = set()

for image in os.listdir(os.path.join(wrk_root, '030_data/data')):
    exts.add(image.split('.')[-1])
    
exts

{'jpg'}

In [124]:
label_df.columns

Index(['filename', '성별', '나이', 'forehead', 'right_eye', 'left_eye',
       'nasolabial', 'perioral', 'right_vol', 'left_vol'],
      dtype='object')

In [125]:
# 전처리 된 이미지의 경로 정리
import re
import math

id_set = set()
image_df = pd.DataFrame(columns=['user_id', 'forehead_path', 'right_eye_path', 'left_eye_path', 'nasolabial_path', 'perioral_path', 'right_vol_path', 'left_vol_path'])

image_dict = {}

# label_df를 가지고 rule base로 이미지 경로를 정리
for i, row in label_df.iterrows():
    # print(row)
    user_id = row['filename'].split('_')[0]
    
    # print(user_id)
    # print()
    for key, value in row[3:].items():
        # print(key, value)
        if math.isnan(value):
            continue
        else:
            image_path = os.path.join('030_data/data', f"{key}_{row['filename']}.jpg")
            abs_path = os.path.join(wrk_root, image_path)
            if not os.path.exists(abs_path):
                print(f"라벨은 존재하지만 이미지가 존재하지 않는다. : {abs_path}")
            else:
                # if user_id not in image_df['user_id'].values:
                #     image_df = image_df.append({'user_id': user_id, f"{key}_path": image_path}, ignore_index=True)
                # else:
                #     image_df.loc[image_df['user_id'] == user_id, f"{key}_path"] = image_path

                if user_id not in image_dict.keys():
                    image_dict[user_id] = {'user_id': user_id}
                
                image_dict[user_id][key] = image_path

In [126]:
num = 0
for user_id, item in image_dict.items():
    for key, value in item.items():
        if key != 'user_id':
            num += 1

print(f"label을 통해 확인한 이미지 개수: {num}, 실제 이미지 개수: {len(os.listdir(os.path.join(wrk_root, '030_data/data')))}")

image_df = pd.DataFrame.from_dict(image_dict, orient='index')
# image_df

image_df = image_df.reset_index(drop=True)
image_df.rename(columns={col:f"{col}_path" for col in image_df.columns[1:]}, inplace=True)
image_df

label을 통해 확인한 이미지 개수: 10932, 실제 이미지 개수: 10932

,user_id,right_eye_path,left_eye_path,nasolabial_path,perioral_path,right_vol_path,left_vol_path,forehead_path
0,0001,030_data/data/right_eye_0001_face.jpg,030_data/data/left_eye_0001_face.jpg,030_data/data/nasolabial_0001_face.jpg,030_data/data/perioral_0001_face.jpg,030_data/data/right_vol_0001_face.jpg,030_data/data/left_vol_0001_face.jpg,NaN
1,0002,030_data/data/right_eye_0002_face.jpg,030_data/data/left_eye_0002_face.jpg,030_data/data/nasolabial_0002_face.jpg,030_data/data/perioral_0002_face.jpg,030_data/data/right_vol_0002_face.jpg,030_data/data/left_vol_0002_face.jpg,030_data/data/forehead_0002_face.jpg
2,0003,030_data/data/right_eye_0003_face.jpg,030_data/data/left_eye_0003_face.jpg,030_data/data/nasolabial_0003_face.jpg,030_data/data/perioral_0003_face.jpg,030_data/data/right_vol_0003_face.jpg,030_data/data/left_vol_0003_face.jpg,NaN
3,0004,030_data/data/right_eye_0004_face.jpg,030_data/data/left_eye_0004_face.jpg,030_data/data/nasolabial_0004_face.jpg,030_data/data/perioral_0004_face.jpg,030_data/data/right_vol_0004_face.jpg,030_data/data/left_vol_0004_face.jpg,NaN
4,0005,030_data/data/right_eye_0005_face.jpg,030_data/data/left_eye_0005_face.jpg,030_data/data/nasolabial_0005_face.jpg,030_data/data/perioral_0005_face.jpg,030_data/data/right_vol_0005_face.jpg,030_data/data/left_vol_0005_face.jpg,NaN
...,...,...,...,...,...,...,...,...
1619,1976,030_data/data/right_eye_1976_face.jpg,030_data/data/left_eye_1976_face.jpg,030_data/data/nasolabial_1976_face.jpg,030_data/data/perioral_1976_face.jpg,030_data/data/right_vol_1976_face.jpg,030_data/data/left_vol_1976_face.jpg,030_data/data/forehead_1976_face.jpg
1620,1977,030_data/data/right_eye_1977_face.jpg,030_data/data/left_eye_1977_face.jpg,030_data/data/nasolabial_1977_face.jpg,030_data/data/perioral_1977_face.jpg,030_data/data/right_vol_1977_face.jpg,030_data/data/left_vol_1977_face.jpg,030_data/data/forehead_1977_face.jpg
1621,1978,030_data/data/right_eye_1978_face.jpg,030_data/data/left_eye_1978_face.jpg,030_data/data/nasolabial_1978_face.jpg,030_data/data/perioral_1978_face.jpg,030_data/data/right_vol_1978_face.jpg,030_data/data/left_vol_1978_face.jpg,NaN
1622,1979,030_data/data/right_eye_1979_face.jpg,030_data/data/left_eye_1979_face.jpg,030_data/data/nasolabial_1979_face.jpg,030_data/data/perioral_1979_face.jpg,030_data/data/right_vol_1979_face.jpg,030_data/data/left_vol_1979_face.jpg,NaN
1623,1980,030_data/data/right_eye_1980_face.jpg,030_data/data/left_eye_1980_face.jpg,030_data/data/nasolabial_1980_face.jpg,030_data/data/perioral_1980_face.jpg,030_data/data/right_vol_1980_face.jpg,030_data/data/left_vol_1980_face.jpg,030_data/data/forehead_1980_face.jpg

In [127]:
label_df['filename'] = label_df['filename'].apply(lambda x:x.split('_')[0])
label_df['성별'] = label_df['성별'].apply(lambda x:'male' if x == '남자' else 'female')

label_df.rename(columns={'filename': 'user_id', '성별': 'gender', '나이': 'age'}, inplace=True)
label_df

,user_id,gender,age,forehead,right_eye,left_eye,nasolabial,perioral,right_vol,left_vol
0,0001,male,9,NaN,0,0.0,0,0.0,0.0,0
1,0002,male,9,0.0,0,0.0,0,0.0,0.0,0
2,0003,male,16,NaN,1,0.0,0,0.0,0.0,0
3,0004,male,17,NaN,1,1.0,0,0.0,0.0,0
4,0005,male,17,NaN,0,0.0,0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...
1619,1976,female,69,3.0,2,2.0,4,3.0,1.0,1
1620,1977,female,70,2.0,2,2.0,3,2.0,2.0,2
1621,1978,female,67,NaN,3,3.0,4,2.0,2.0,2
1622,1979,female,70,NaN,3,3.0,3,3.0,1.0,1
1623,1980,female,73,2.0,2,2.0,3,4.0,3.0,3

In [128]:
merged_df = pd.merge(image_df[['user_id', 'forehead_path', 'right_eye_path', 'left_eye_path', 'nasolabial_path', 'perioral_path', 'right_vol_path', 'left_vol_path']], label_df, on='user_id')
merged_df = merged_df[['user_id', 'age', 'gender', 'forehead_path', 'right_eye_path', 'left_eye_path', 'nasolabial_path', 'perioral_path', 'right_vol_path', 'left_vol_path', 'forehead', 'right_eye', 'left_eye', 'nasolabial', 'perioral', 'right_vol', 'left_vol']]

merged_df.fillna(-1, inplace=True)
merged_df = merged_df.astype({
    'forehead': 'int', 
    'right_eye': 'int', 
    'left_eye': 'int', 
    'nasolabial': 'int', 
    'perioral': 'int', 
    'right_vol': 'int', 
    'left_vol': 'int'
})
merged_df

,user_id,age,gender,forehead_path,right_eye_path,left_eye_path,nasolabial_path,perioral_path,right_vol_path,left_vol_path,forehead,right_eye,left_eye,nasolabial,perioral,right_vol,left_vol
0,0001,9,male,-1,030_data/data/right_eye_0001_face.jpg,030_data/data/left_eye_0001_face.jpg,030_data/data/nasolabial_0001_face.jpg,030_data/data/perioral_0001_face.jpg,030_data/data/right_vol_0001_face.jpg,030_data/data/left_vol_0001_face.jpg,-1,0,0,0,0,0,0
1,0002,9,male,030_data/data/forehead_0002_face.jpg,030_data/data/right_eye_0002_face.jpg,030_data/data/left_eye_0002_face.jpg,030_data/data/nasolabial_0002_face.jpg,030_data/data/perioral_0002_face.jpg,030_data/data/right_vol_0002_face.jpg,030_data/data/left_vol_0002_face.jpg,0,0,0,0,0,0,0
2,0003,16,male,-1,030_data/data/right_eye_0003_face.jpg,030_data/data/left_eye_0003_face.jpg,030_data/data/nasolabial_0003_face.jpg,030_data/data/perioral_0003_face.jpg,030_data/data/right_vol_0003_face.jpg,030_data/data/left_vol_0003_face.jpg,-1,1,0,0,0,0,0
3,0004,17,male,-1,030_data/data/right_eye_0004_face.jpg,030_data/data/left_eye_0004_face.jpg,030_data/data/nasolabial_0004_face.jpg,030_data/data/perioral_0004_face.jpg,030_data/data/right_vol_0004_face.jpg,030_data/data/left_vol_0004_face.jpg,-1,1,1,0,0,0,0
4,0005,17,male,-1,030_data/data/right_eye_0005_face.jpg,030_data/data/left_eye_0005_face.jpg,030_data/data/nasolabial_0005_face.jpg,030_data/data/perioral_0005_face.jpg,030_data/data/right_vol_0005_face.jpg,030_data/data/left_vol_0005_face.jpg,-1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1619,1976,69,female,030_data/data/forehead_1976_face.jpg,030_data/data/right_eye_1976_face.jpg,030_data/data/left_eye_1976_face.jpg,030_data/data/nasolabial_1976_face.jpg,030_data/data/perioral_1976_face.jpg,030_data/data/right_vol_1976_face.jpg,030_data/data/left_vol_1976_face.jpg,3,2,2,4,3,1,1
1620,1977,70,female,030_data/data/forehead_1977_face.jpg,030_data/data/right_eye_1977_face.jpg,030_data/data/left_eye_1977_face.jpg,030_data/data/nasolabial_1977_face.jpg,030_data/data/perioral_1977_face.jpg,030_data/data/right_vol_1977_face.jpg,030_data/data/left_vol_1977_face.jpg,2,2,2,3,2,2,2
1621,1978,67,female,-1,030_data/data/right_eye_1978_face.jpg,030_data/data/left_eye_1978_face.jpg,030_data/data/nasolabial_1978_face.jpg,030_data/data/perioral_1978_face.jpg,030_data/data/right_vol_1978_face.jpg,030_data/data/left_vol_1978_face.jpg,-1,3,3,4,2,2,2
1622,1979,70,female,-1,030_data/data/right_eye_1979_face.jpg,030_data/data/left_eye_1979_face.jpg,030_data/data/nasolabial_1979_face.jpg,030_data/data/perioral_1979_face.jpg,030_data/data/right_vol_1979_face.jpg,030_data/data/left_vol_1979_face.jpg,-1,3,3,3,3,1,1
1623,1980,73,female,030_data/data/forehead_1980_face.jpg,030_data/data/right_eye_1980_face.jpg,030_data/data/left_eye_1980_face.jpg,030_data/data/nasolabial_1980_face.jpg,030_data/data/perioral_1980_face.jpg,030_data/data/right_vol_1980_face.jpg,030_data/data/left_vol_1980_face.jpg,2,2,2,3,4,3,3

In [129]:
import json

with open(os.path.join(wrk_root, '030_data/label/wrinkle_label.json'), 'w') as f:
    json.dump(merged_df.to_dict(orient='records'), f, indent=2, ensure_ascii=False)

### 028

In [130]:
import os
import pandas as pd
# meta data 가져오기

wrk_root = "/home/work/hocheol_dir/workspace/datasets/v0.2_data/wrinkle"

label_path = "/home/work/hocheol_dir/workspace/datasets/v0.2_data/wrinkle/NIA_skin_measurement_wrinkle_250817 - 시트1.csv"
label_df = pd.read_csv(label_path)
label_df.rename(columns={'periroal': 'perioral'}, inplace=True)
label_df.head()

,filename,forehead,right_eye,left_eye,nasolabial,perioral,right_vol,left_vol
0,0001_01_F.jpg,2.0,2.0,2.0,3.0,2.0,2.0,2.0
1,0001_02_F.jpg,2.0,2.0,2.0,3.0,2.0,1.0,1.0
2,0001_03_F.jpg,3.0,2.0,2.0,3.0,2.0,2.0,2.0
3,0002_01_F.jpg,2.0,2.0,3.0,2.0,2.0,2.0,2.0
4,0002_02_F.jpg,2.0,2.0,2.0,2.0,2.0,2.0,2.0

In [131]:
os.makedirs(os.path.join(wrk_root, '028_data/data'), exist_ok=True)

In [132]:
label_df.columns

Index(['filename', 'forehead', 'right_eye', 'left_eye', 'nasolabial',
       'perioral', 'right_vol', 'left_vol'],
      dtype='object')

In [133]:
label_df = label_df[~label_df.isnull().any(axis=1)]
# label_df['image_path'] = label_df['filename'].apply(get_image_path)
# label_df['image_path'].apply(lambda x:os.path.exists(os.path.join('/home/work/hocheol_dir/workspace/datasets/_origin_data', x))).value_counts()

In [134]:
label_df.sample(2)

,filename,forehead,right_eye,left_eye,nasolabial,perioral,right_vol,left_vol
1868,0714_03_F.jpg,2.0,1.0,1.0,3.0,2.0,2.0,2.0
1058,0408_03_F.jpg,3.0,3.0,2.0,2.0,1.0,3.0,3.0

In [135]:
# 전처리 된 이미지의 경로 정리
import re
import math

id_set = set()
image_df = pd.DataFrame(columns=['user_id', 'forehead_path', 'right_eye_path', 'left_eye_path', 'nasolabial_path', 'perioral_path', 'right_vol_path', 'left_vol_path'])

image_dict = {}

# label_df를 가지고 rule base로 이미지 경로를 정리
for i, row in label_df.iterrows():
    # print(row)
    user_id = row['filename'].split('_')[0]
    image_id = re.search(r'[0-9]+_[0-9]+', row['filename']).group(0)
    
    for key, value in row[1:].items():
        # print(key, value)
        if math.isnan(value):
            continue
        else:
            image_path = os.path.join('028_data/data', f"{key}_{row['filename']}.jpg")
            abs_path = os.path.join(wrk_root, image_path)
            if not os.path.exists(abs_path):
                print(f"라벨은 존재하지만 이미지가 존재하지 않는다. : {abs_path}")
            else:
                if image_id not in image_dict.keys():
                    image_dict[image_id] = {'user_id': user_id, 'image_id': image_id}
                
                image_dict[image_id][key] = image_path

In [136]:
num = 0
for image_id, item in image_dict.items():
    for key, value in item.items():
        if 'id' not in key:
            num += 1

print(f"label을 통해 확인한 이미지 개수: {num}, 실제 이미지 개수: {len(os.listdir(os.path.join(wrk_root, '028_data/data')))}")

image_df = pd.DataFrame.from_dict(image_dict, orient='index')
# image_df

image_df = image_df.reset_index(drop=True)
image_df.rename(columns={col:f"{col}_path" for col in image_df.columns[2:]}, inplace=True)
image_df

label을 통해 확인한 이미지 개수: 20020, 실제 이미지 개수: 20020

,user_id,image_id,forehead_path,right_eye_path,left_eye_path,nasolabial_path,perioral_path,right_vol_path,left_vol_path
0,0001,0001_01,028_data/data/forehead_0001_01_F.jpg.jpg,028_data/data/right_eye_0001_01_F.jpg.jpg,028_data/data/left_eye_0001_01_F.jpg.jpg,028_data/data/nasolabial_0001_01_F.jpg.jpg,028_data/data/perioral_0001_01_F.jpg.jpg,028_data/data/right_vol_0001_01_F.jpg.jpg,028_data/data/left_vol_0001_01_F.jpg.jpg
1,0001,0001_02,028_data/data/forehead_0001_02_F.jpg.jpg,028_data/data/right_eye_0001_02_F.jpg.jpg,028_data/data/left_eye_0001_02_F.jpg.jpg,028_data/data/nasolabial_0001_02_F.jpg.jpg,028_data/data/perioral_0001_02_F.jpg.jpg,028_data/data/right_vol_0001_02_F.jpg.jpg,028_data/data/left_vol_0001_02_F.jpg.jpg
2,0001,0001_03,028_data/data/forehead_0001_03_F.jpg.jpg,028_data/data/right_eye_0001_03_F.jpg.jpg,028_data/data/left_eye_0001_03_F.jpg.jpg,028_data/data/nasolabial_0001_03_F.jpg.jpg,028_data/data/perioral_0001_03_F.jpg.jpg,028_data/data/right_vol_0001_03_F.jpg.jpg,028_data/data/left_vol_0001_03_F.jpg.jpg
3,0002,0002_01,028_data/data/forehead_0002_01_F.jpg.jpg,028_data/data/right_eye_0002_01_F.jpg.jpg,028_data/data/left_eye_0002_01_F.jpg.jpg,028_data/data/nasolabial_0002_01_F.jpg.jpg,028_data/data/perioral_0002_01_F.jpg.jpg,028_data/data/right_vol_0002_01_F.jpg.jpg,028_data/data/left_vol_0002_01_F.jpg.jpg
4,0002,0002_02,028_data/data/forehead_0002_02_F.jpg.jpg,028_data/data/right_eye_0002_02_F.jpg.jpg,028_data/data/left_eye_0002_02_F.jpg.jpg,028_data/data/nasolabial_0002_02_F.jpg.jpg,028_data/data/perioral_0002_02_F.jpg.jpg,028_data/data/right_vol_0002_02_F.jpg.jpg,028_data/data/left_vol_0002_02_F.jpg.jpg
...,...,...,...,...,...,...,...,...,...
2855,1099,1099_02,028_data/data/forehead_1099_02_F.jpg.jpg,028_data/data/right_eye_1099_02_F.jpg.jpg,028_data/data/left_eye_1099_02_F.jpg.jpg,028_data/data/nasolabial_1099_02_F.jpg.jpg,028_data/data/perioral_1099_02_F.jpg.jpg,028_data/data/right_vol_1099_02_F.jpg.jpg,028_data/data/left_vol_1099_02_F.jpg.jpg
2856,1099,1099_03,028_data/data/forehead_1099_03_F.jpg.jpg,028_data/data/right_eye_1099_03_F.jpg.jpg,028_data/data/left_eye_1099_03_F.jpg.jpg,028_data/data/nasolabial_1099_03_F.jpg.jpg,028_data/data/perioral_1099_03_F.jpg.jpg,028_data/data/right_vol_1099_03_F.jpg.jpg,028_data/data/left_vol_1099_03_F.jpg.jpg
2857,1100,1100_01,028_data/data/forehead_1100_01_F.jpg.jpg,028_data/data/right_eye_1100_01_F.jpg.jpg,028_data/data/left_eye_1100_01_F.jpg.jpg,028_data/data/nasolabial_1100_01_F.jpg.jpg,028_data/data/perioral_1100_01_F.jpg.jpg,028_data/data/right_vol_1100_01_F.jpg.jpg,028_data/data/left_vol_1100_01_F.jpg.jpg
2858,1100,1100_02,028_data/data/forehead_1100_02_F.jpg.jpg,028_data/data/right_eye_1100_02_F.jpg.jpg,028_data/data/left_eye_1100_02_F.jpg.jpg,028_data/data/nasolabial_1100_02_F.jpg.jpg,028_data/data/perioral_1100_02_F.jpg.jpg,028_data/data/right_vol_1100_02_F.jpg.jpg,028_data/data/left_vol_1100_02_F.jpg.jpg
2859,1100,1100_03,028_data/data/forehead_1100_03_F.jpg.jpg,028_data/data/right_eye_1100_03_F.jpg.jpg,028_data/data/left_eye_1100_03_F.jpg.jpg,028_data/data/nasolabial_1100_03_F.jpg.jpg,028_data/data/perioral_1100_03_F.jpg.jpg,028_data/data/right_vol_1100_03_F.jpg.jpg,028_data/data/left_vol_1100_03_F.jpg.jpg

In [137]:
label_df.head(2)

,filename,forehead,right_eye,left_eye,nasolabial,perioral,right_vol,left_vol
0,0001_01_F.jpg,2.0,2.0,2.0,3.0,2.0,2.0,2.0
1,0001_02_F.jpg,2.0,2.0,2.0,3.0,2.0,1.0,1.0

In [139]:
image_df.sample(2)

,user_id,image_id,forehead_path,right_eye_path,left_eye_path,nasolabial_path,perioral_path,right_vol_path,left_vol_path
2138,0826,0826_01,028_data/data/forehead_0826_01_F.jpg.jpg,028_data/data/right_eye_0826_01_F.jpg.jpg,028_data/data/left_eye_0826_01_F.jpg.jpg,028_data/data/nasolabial_0826_01_F.jpg.jpg,028_data/data/perioral_0826_01_F.jpg.jpg,028_data/data/right_vol_0826_01_F.jpg.jpg,028_data/data/left_vol_0826_01_F.jpg.jpg
1827,0710,0710_02,028_data/data/forehead_0710_02_F.jpg.jpg,028_data/data/right_eye_0710_02_F.jpg.jpg,028_data/data/left_eye_0710_02_F.jpg.jpg,028_data/data/nasolabial_0710_02_F.jpg.jpg,028_data/data/perioral_0710_02_F.jpg.jpg,028_data/data/right_vol_0710_02_F.jpg.jpg,028_data/data/left_vol_0710_02_F.jpg.jpg

In [140]:
label_df['image_id'] = label_df['filename'].apply(lambda x: re.search(r'[0-9]+_[0-9]+', x).group(0))
label_df.head(3)

,filename,forehead,right_eye,left_eye,nasolabial,perioral,right_vol,left_vol,image_id
0,0001_01_F.jpg,2.0,2.0,2.0,3.0,2.0,2.0,2.0,0001_01
1,0001_02_F.jpg,2.0,2.0,2.0,3.0,2.0,1.0,1.0,0001_02
2,0001_03_F.jpg,3.0,2.0,2.0,3.0,2.0,2.0,2.0,0001_03

In [141]:
merged_df = pd.merge(image_df[['user_id', 'image_id', 'forehead_path', 'right_eye_path', 'left_eye_path', 'nasolabial_path', 'perioral_path', 'right_vol_path', 'left_vol_path']], label_df, on='image_id')
merged_df = merged_df[['user_id', 'image_id', 'forehead_path', 'right_eye_path', 'left_eye_path', 'nasolabial_path', 'perioral_path', 'right_vol_path', 'left_vol_path', 'forehead', 'right_eye', 'left_eye', 'nasolabial', 'perioral', 'right_vol', 'left_vol']]

merged_df.fillna(-1, inplace=True)
merged_df = merged_df.astype({
    'forehead': 'int', 
    'right_eye': 'int', 
    'left_eye': 'int', 
    'nasolabial': 'int', 
    'perioral': 'int', 
    'right_vol': 'int', 
    'left_vol': 'int'
})
merged_df

,user_id,image_id,forehead_path,right_eye_path,left_eye_path,nasolabial_path,perioral_path,right_vol_path,left_vol_path,forehead,right_eye,left_eye,nasolabial,perioral,right_vol,left_vol
0,0001,0001_01,028_data/data/forehead_0001_01_F.jpg.jpg,028_data/data/right_eye_0001_01_F.jpg.jpg,028_data/data/left_eye_0001_01_F.jpg.jpg,028_data/data/nasolabial_0001_01_F.jpg.jpg,028_data/data/perioral_0001_01_F.jpg.jpg,028_data/data/right_vol_0001_01_F.jpg.jpg,028_data/data/left_vol_0001_01_F.jpg.jpg,2,2,2,3,2,2,2
1,0001,0001_02,028_data/data/forehead_0001_02_F.jpg.jpg,028_data/data/right_eye_0001_02_F.jpg.jpg,028_data/data/left_eye_0001_02_F.jpg.jpg,028_data/data/nasolabial_0001_02_F.jpg.jpg,028_data/data/perioral_0001_02_F.jpg.jpg,028_data/data/right_vol_0001_02_F.jpg.jpg,028_data/data/left_vol_0001_02_F.jpg.jpg,2,2,2,3,2,1,1
2,0001,0001_03,028_data/data/forehead_0001_03_F.jpg.jpg,028_data/data/right_eye_0001_03_F.jpg.jpg,028_data/data/left_eye_0001_03_F.jpg.jpg,028_data/data/nasolabial_0001_03_F.jpg.jpg,028_data/data/perioral_0001_03_F.jpg.jpg,028_data/data/right_vol_0001_03_F.jpg.jpg,028_data/data/left_vol_0001_03_F.jpg.jpg,3,2,2,3,2,2,2
3,0002,0002_01,028_data/data/forehead_0002_01_F.jpg.jpg,028_data/data/right_eye_0002_01_F.jpg.jpg,028_data/data/left_eye_0002_01_F.jpg.jpg,028_data/data/nasolabial_0002_01_F.jpg.jpg,028_data/data/perioral_0002_01_F.jpg.jpg,028_data/data/right_vol_0002_01_F.jpg.jpg,028_data/data/left_vol_0002_01_F.jpg.jpg,2,2,3,2,2,2,2
4,0002,0002_02,028_data/data/forehead_0002_02_F.jpg.jpg,028_data/data/right_eye_0002_02_F.jpg.jpg,028_data/data/left_eye_0002_02_F.jpg.jpg,028_data/data/nasolabial_0002_02_F.jpg.jpg,028_data/data/perioral_0002_02_F.jpg.jpg,028_data/data/right_vol_0002_02_F.jpg.jpg,028_data/data/left_vol_0002_02_F.jpg.jpg,2,2,2,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2855,1099,1099_02,028_data/data/forehead_1099_02_F.jpg.jpg,028_data/data/right_eye_1099_02_F.jpg.jpg,028_data/data/left_eye_1099_02_F.jpg.jpg,028_data/data/nasolabial_1099_02_F.jpg.jpg,028_data/data/perioral_1099_02_F.jpg.jpg,028_data/data/right_vol_1099_02_F.jpg.jpg,028_data/data/left_vol_1099_02_F.jpg.jpg,1,0,0,0,0,1,1
2856,1099,1099_03,028_data/data/forehead_1099_03_F.jpg.jpg,028_data/data/right_eye_1099_03_F.jpg.jpg,028_data/data/left_eye_1099_03_F.jpg.jpg,028_data/data/nasolabial_1099_03_F.jpg.jpg,028_data/data/perioral_1099_03_F.jpg.jpg,028_data/data/right_vol_1099_03_F.jpg.jpg,028_data/data/left_vol_1099_03_F.jpg.jpg,1,0,0,0,0,1,1
2857,1100,1100_01,028_data/data/forehead_1100_01_F.jpg.jpg,028_data/data/right_eye_1100_01_F.jpg.jpg,028_data/data/left_eye_1100_01_F.jpg.jpg,028_data/data/nasolabial_1100_01_F.jpg.jpg,028_data/data/perioral_1100_01_F.jpg.jpg,028_data/data/right_vol_1100_01_F.jpg.jpg,028_data/data/left_vol_1100_01_F.jpg.jpg,1,1,1,1,0,1,1
2858,1100,1100_02,028_data/data/forehead_1100_02_F.jpg.jpg,028_data/data/right_eye_1100_02_F.jpg.jpg,028_data/data/left_eye_1100_02_F.jpg.jpg,028_data/data/nasolabial_1100_02_F.jpg.jpg,028_data/data/perioral_1100_02_F.jpg.jpg,028_data/data/right_vol_1100_02_F.jpg.jpg,028_data/data/left_vol_1100_02_F.jpg.jpg,1,1,0,1,0,1,1
2859,1100,1100_03,028_data/data/forehead_1100_03_F.jpg.jpg,028_data/data/right_eye_1100_03_F.jpg.jpg,028_data/data/left_eye_1100_03_F.jpg.jpg,028_data/data/nasolabial_1100_03_F.jpg.jpg,028_data/data/perioral_1100_03_F.jpg.jpg,028_data/data/right_vol_1100_03_F.jpg.jpg,028_data/data/left_vol_1100_03_F.jpg.jpg,0,1,0,1,0,1,1

In [156]:
merged_df.loc[:, 'forehead':].describe()

,forehead,right_eye,left_eye,nasolabial,perioral,right_vol,left_vol
count,2860.000000,2860.000000,2860.000000,2860.000000,2860.000000,2860.000000,2860.000000
mean,1.310140,1.556643,1.383217,1.700000,1.208741,1.444406,1.595455
std,1.107371,1.061558,1.060927,1.060697,1.098885,1.110250,1.130044
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000
50%,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,2.000000
75%,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000
max,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000

In [157]:
import json

os.makedirs(os.path.join(wrk_root, '028_data/label'), exist_ok=True)
with open(os.path.join(wrk_root, '028_data/label/wrinkle_label.json'), 'w') as f:
    json.dump(merged_df.to_dict(orient='records'), f, indent=2, ensure_ascii=False)